#LAMP Server
#mysql server address: mysql_db:3306
#mysql username: root
#mysql password: Appdev
#Execute and associate the sql script
#CREATE DATABASE IF NOT EXISTS `test`;
#GRANT ALL ON `test`.* TO 'user'@'%';

version: "3"
services:
  #MYSQL
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    #    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Appdev
    volumes:
      - ./:/docker-entrypoint-initdb.d

  #PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    #    restart: always
    environment:
      - PMA_HOST=mysql_db
      - MYSQL_ROOT_PASSWORD=Appdev
      - PMA_PORT=3306
    ports:
      - 8080:80

  #PHP_APACHE
  php-apache:
    build: .
    container_name: php-apache
    #    restart: always
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
    links:
      - mysql_db
    depends_on:
      - mysql_db
